apiVersion: v1
kind: Service
metadata:
  name: k8s-symfony-lb
  labels:
    app: k8s-symfony
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-2:121996518446:certificate/b222e330-ceb0-4f1c-a206-e8046d6cc1bd"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
  selector:
    app: k8s-symfony
  type: LoadBalancer
