apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: k8s-symfony-deployment
spec:
  selector:
    matchLabels:
      app: k8s-symfony
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-symfony
    spec:
      containers:
        - name: k8s-symfony
          image: xxx.dkr.ecr.eu-west-2.amazonaws.com/xxx:1.0.0
          ports:
            - containerPort: 80
          env:
            - name: APP_ENV
              value: prod
          readinessProbe:
            httpGet:
              path: /_/health
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /_/health
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 15
